import PDFDocument from "pdfkit";

export type ReceiptLine = {
  label: string;
  amount: number;
  kind?: "charge" | "deduction" | "subtotal" | "total";
};

export type ReceiptDocumentInput = {
  title: string;
  receiptNumber: string;
  issuedAt: Date;
  payerName: string;
  payeeName: string;
  propertyTitle?: string;
  propertyAddress?: string;
  reference?: string;
  currency: string;
  lines: ReceiptLine[];
  totalAmount: number;
  purposeLabel: string;
  rentPeriodLabel?: string;
  signatures?: Array<{
    role: string;
    name: string;
    signedAt?: Date | null;
  }>;
  footerNote?: string;
};

function formatMoney(amount: number, currency = "NGN") {
  try {
    return new Intl.NumberFormat("en-NG", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `${currency} ${amount.toLocaleString()}`;
  }
}

function formatDate(value: Date) {
  return value.toLocaleString("en-NG", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export async function generateReceiptPdf(
  input: ReceiptDocumentInput
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const navy = "#0B1F3A";
    const teal = "#008585";
    const muted = "#5A6A7D";

    doc.rect(0, 0, doc.page.width, 88).fill(navy);
    doc.fillColor("#F4E9D8").fontSize(22).text("House In Hand", 48, 34);
    doc.fontSize(10).fillColor("#CFE7E7").text("Official payment receipt", 48, 62);

    doc.fillColor(navy).fontSize(18).text(input.title, 48, 110);
    doc
      .fontSize(10)
      .fillColor(muted)
      .text(`Receipt ${input.receiptNumber}`, 48, 136)
      .text(`Issued ${formatDate(input.issuedAt)}`, 48, 150);

    doc
      .roundedRect(48, 178, doc.page.width - 96, 92, 8)
      .fillAndStroke("#FAF6EF", "#E0D4C2");

    doc.fillColor(muted).fontSize(9).text("PAYER", 64, 194);
    doc.fillColor(navy).fontSize(12).text(input.payerName, 64, 208);
    doc.fillColor(muted).fontSize(9).text("PAYEE", 320, 194);
    doc.fillColor(navy).fontSize(12).text(input.payeeName, 320, 208);

    if (input.propertyTitle) {
      doc.fillColor(muted).fontSize(9).text("PROPERTY", 64, 238);
      doc
        .fillColor(navy)
        .fontSize(11)
        .text(
          input.propertyAddress
            ? `${input.propertyTitle}\n${input.propertyAddress}`
            : input.propertyTitle,
          64,
          250,
          { width: 420 }
        );
    }

    let y = 292;
    doc.fillColor(navy).fontSize(12).text("Cost breakdown", 48, y);
    y += 22;

    doc.moveTo(48, y).lineTo(doc.page.width - 48, y).strokeColor("#E0D4C2").stroke();
    y += 14;

    for (const line of input.lines) {
      const isTotal = line.kind === "total";
      doc
        .fillColor(isTotal ? navy : muted)
        .fontSize(isTotal ? 11 : 10)
        .text(line.label, 48, y, { width: 360 });
      doc
        .fillColor(isTotal ? teal : navy)
        .fontSize(isTotal ? 12 : 10)
        .text(formatMoney(line.amount, input.currency), 48, y, {
          width: doc.page.width - 96,
          align: "right",
        });
      y += isTotal ? 24 : 18;
    }

    y += 8;
    doc
      .fillColor(muted)
      .fontSize(10)
      .text(`Purpose: ${input.purposeLabel}`, 48, y);
    y += 16;
    if (input.rentPeriodLabel) {
      doc.text(`Rent period: ${input.rentPeriodLabel}`, 48, y);
      y += 16;
    }
    if (input.reference) {
      doc.text(`Reference: ${input.reference}`, 48, y);
      y += 16;
    }

    if (input.signatures?.length) {
      y += 12;
      doc.fillColor(navy).fontSize(12).text("Signatures", 48, y);
      y += 20;
      for (const sig of input.signatures) {
        doc
          .roundedRect(48, y, 220, 58, 6)
          .strokeColor("#D4C4AE")
          .stroke();
        doc.fillColor(muted).fontSize(8).text(sig.role.toUpperCase(), 58, y + 10);
        doc
          .fillColor(navy)
          .fontSize(11)
          .text(sig.name || "—", 58, y + 24);
        if (sig.signedAt) {
          doc
            .fillColor(muted)
            .fontSize(8)
            .text(formatDate(new Date(sig.signedAt)), 58, y + 40);
        }
        y += 72;
      }
    }

    doc
      .fillColor(muted)
      .fontSize(9)
      .text(
        input.footerNote ||
          "This receipt was generated by House In Hand. Keep it for your records.",
        48,
        doc.page.height - 72,
        { width: doc.page.width - 96, align: "center" }
      );

    doc.end();
  });
}

export async function generateAgreementPdf(input: {
  title: string;
  documentNumber: string;
  termsText: string;
  rentAmount: number;
  currency: string;
  paymentPeriod: string;
  startDate: Date;
  endDate?: Date | null;
  legalProvider: "hih" | "own_legal";
  legalCompanyName?: string | null;
  tenantSignatureName?: string;
  landlordSignatureName?: string;
  tenantSignedAt?: Date | null;
  landlordSignedAt?: Date | null;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 72).fill("#0B1F3A");
    doc.fillColor("#F4E9D8").fontSize(20).text("House In Hand", 48, 24);
    doc.fontSize(10).fillColor("#CFE7E7").text("Tenancy agreement", 48, 50);

    doc.fillColor("#0B1F3A").fontSize(16).text(input.title, 48, 92);
    doc
      .fontSize(10)
      .fillColor("#5A6A7D")
      .text(`Document ${input.documentNumber}`, 48, 114);

    doc
      .fontSize(10)
      .fillColor("#0B1F3A")
      .text(
        `Rent: ${formatMoney(input.rentAmount, input.currency)} / ${input.paymentPeriod}`,
        48,
        136
      )
      .text(
        `Term: ${input.startDate.toLocaleDateString()} – ${
          input.endDate ? new Date(input.endDate).toLocaleDateString() : "—"
        }`,
        48,
        152
      )
      .text(
        input.legalProvider === "hih"
          ? "Legal handling: House In Hand"
          : `Legal handling: ${input.legalCompanyName || "Landlord-appointed firm"}`,
        48,
        168
      );

    doc.fontSize(11).fillColor("#0B1F3A").text(input.termsText, 48, 198, {
      width: doc.page.width - 96,
      lineGap: 4,
    });

    const sigY = doc.page.height - 180;
    doc.fillColor("#0B1F3A").fontSize(12).text("Signatures", 48, sigY);

    const boxes = [
      {
        role: "Tenant",
        name: input.tenantSignatureName,
        signedAt: input.tenantSignedAt,
        x: 48,
      },
      {
        role: "Landlord",
        name: input.landlordSignatureName,
        signedAt: input.landlordSignedAt,
        x: 320,
      },
    ];

    for (const box of boxes) {
      doc.roundedRect(box.x, sigY + 22, 220, 70, 6).strokeColor("#D4C4AE").stroke();
      doc.fillColor("#5A6A7D").fontSize(8).text(box.role.toUpperCase(), box.x + 10, sigY + 32);
      doc.fillColor("#0B1F3A").fontSize(11).text(box.name || "—", box.x + 10, sigY + 46);
      if (box.signedAt) {
        doc
          .fillColor("#5A6A7D")
          .fontSize(8)
          .text(new Date(box.signedAt).toLocaleString(), box.x + 10, sigY + 64);
      }
    }

    doc.end();
  });
}
